### ISSUE TITLE
Клонирование репозитория

### ISSUE THREAD

**Issue by Soldat72** [PanarinM/courses_homeworks#12]
в чистую папку на свой комп склонировал репозиторий с ГХ где было две ветки: мастер и моя рабочая
но в результате, перенеслась только ветка мастер, а рабочая нет. также не перенеслись рабочии файлы.
что делаю не так?

**Comment by PanarinM** [comment]
@Soldat72 не совсем понимаю что и откуда вы клонили :)
Подробнее пожалуйста )

**Comment by Soldat72** [comment]
решил проделать следующее:
1 в терминале зашел в новую папку на своем компе (не под гитом) 
2. набрал в терминале git clone https://github.com/Soldat72/courses_homeworks.git (ссылку получил по кнопке Clone на Гитхабе в своем репозитории
3. на локальный комп склонировалась папка "courses_homeworks "с веткой master. Но второй ветки там нет, как и нет рабочей папки с файлами, которая есть на гитхабе в этой рабочей ветке

**Comment by PanarinM** [comment]
а если написать `git branch -a`?
или `git log --graph --oneline --decorate --all `?

:)

**Comment by Soldat72** [comment]
если написать git branch -a то выдает :
* master
  remotes/origin/HEAD -> origin/master
  remotes/origin/andr_hw
  remotes/origin/master

git log --graph --oneline --decorate --all:

0fd8ed9 (origin/andr_hw) dz2 #4
* 636ab6d dz2 #3
* 526e77e dz2 #1
* 92f1909 DZ 1- done,3-done,4- half done
* 8c56312 First homework after commit --ammend added folder  with name and two files in it
* 5d70ace (HEAD -> master, origin/master, origin/HEAD) initial commit

**Comment by PanarinM** [comment]
ну вот он вам все ветки и выдал

**Comment by Soldat72** [comment]
а файлы где?

**Comment by PanarinM** [comment]
Такс, вы похоже забыли что из себя представляют ветки, коммиты и как гит работает с файлами

**Comment by PanarinM** [comment]
напишите `git checkout andr_hw`

**Comment by Soldat72** [comment]
не забыл :-) просто я думал что файлы видны вне зависимости на какой ветке ты стоишь и команда в терминале ls покажет их по-любому. 
но пока на ветку не переключился то файлов не видел.

**Comment by Soldat72** [comment]
1. получается Гит извлекает рабочии файлы для показа и дальнейшей работы только если перейти на эту  ветку?
2. Почемы остальные ветки как то обозначены обособленно красным цветом и ремоут remotes/origin/andr_hw ?

**Comment by PanarinM** [comment]
1. Как бы да и как бы нет. По сути, по вам для работы - да, технически - нет, он применяет дельты и как бы собирает файлы по коммитам.

2. Это вы легко можете найти в документации )
`git clone *ссылка*`
Это всего лишь сокращение. На самом деле гит выполняет:
`git init *папка*`
`git remote add origin *ссылка*`
`git pull`

Таким образом вы получаете ветку мастер up to date с вашим ремоутом, а остальные просто фетчатся как удаленные. Когда вы делаете чекаут - гит смотрит есть ли вас такая ветка локально, если нет - есть ли такая в ремоутах, если нет - ошибка

**Comment by PanarinM** [comment]
Закройте issue если получили ответ )

**Comment by Soldat72** [comment]
!!!!!! спасибо. круто!
