### ISSUE TITLE
Amend переписывает историю. ....

### ISSUE THREAD

**Issue by Soldat72** [PanarinM/courses_homeworks#7]
_Originally posted by @PanarinM in https://github.com/PanarinM/courses_homeworks/pull/2#issuecomment-424607669_

прочитал в мануале такое : "git commit --amend меняет SHA-1 коммита. Тут как с маленьким перемещением (rebase) — не правьте последний коммит, если вы его уже куда-то отправили...."
получается я запушил комит себе в ориджин на GH  и запулил на ваш репозиторий. А потом   переписываю свой комит через --amend  и пушу через форс опять на GH. И это как раз то, что не рекомендует мануал.... Как тут быть? Или пока он на remote ветках не поменян, то все ОК?

**Comment by PanarinM** [comment]
Мануал вам в целом не рекоммендует форс-пушить. Если вы единственный кто работает с этой веткой - нет ничего страшного в форс-пуше
